version: "3.8"
services:
  npm-cli:
    container_name: npm_cli
    build:
      context: .
      dockerfile: ./docker/utility-containers/npm.Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./:/app
