version: "3.8"

services:
  backend:
    container_name: express
    build:
      context: .
      dockerfile: ./docker/backend/express.Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./backend/src:/app/src
      - /app/node_modules
    env_file:
      - ./env-files/backend.env
  frontend:
    container_name: react
    build:
      context: .
      dockerfile: ./docker/frontend/react.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - /app/node_modules
    env_file:
      - ./env-files/frontend.env
    stdin_open: true
    tty: true
    depends_on:
      - backend
