version: "3.8"
services:
  npm-cli:
    container_name: npm-cli
    build:
      context: .
      dockerfile: ./docker/utility-containers/npm.Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./backend:/app
  backend:
    container_name: express
    build:
      context: .
      dockerfile: ./docker/backend/express.Dockerfile
    ports:
      - '80:80'
    volumes:
      - ./backend/src:/app/src
      - /app/node_modules
    env_file:
      - ./env-files/backend.env
