version: "3.8"

services:
  mongodb:
    container_name: mongodb
    image: 'mongo'
    volumes:
      - mongodb-data:/data/db
    env_file:
      - ./env-files/mongo.env
    networks:
      - api-network
  backend:
    container_name: express
    build:
      context: .
      dockerfile: ./docker/backend/express.Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./backend/src:/app/src
      - /app/node_modules
      - logs:/app/src/logs
    env_file:
      - ./env-files/backend.env
    depends_on:
      - mongodb
    networks:
      - api-network
  frontend:
    container_name: react
    build:
      context: .
      dockerfile: ./docker/frontend/react.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - /app/node_modules
    env_file:
      - ./env-files/frontend.env
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  mongodb-data:
  logs:

networks:
  api-network:
